DROP TABLE IF EXISTS clinics;
CREATE TABLE clinics (
    id SERIAL PRIMARY KEY,
    name TEXT NOT NULL,
    number_of_doctors INT,
    avg_doctor_score FLOAT,
    annual_cycles INT,
    national_annual_cycles INT,
    avg_rating FLOAT,
    address TEXT,
    num_reviews INT,
    cdc_success_rates JSONB,
    avg_cdc_success_rate FLOAT,
    national_cdc_success_rates JSONB,
    avg_national_cdc_success_rate FLOAT,
    is_gaia_partner BOOLEAN,
    city TEXT,
    state TEXT,
    zip_code TEXT,
    lat_city FLOAT,
    lon_city FLOAT,
    lat_state FLOAT,
    lon_state FLOAT,
    lat_zip FLOAT,
    lon_zip FLOAT,
    lat_city_state FLOAT,
    lon_city_state FLOAT,
    lat_city_state_zip FLOAT,
    lon_city_state_zip FLOAT,
    lat_address FLOAT,
    lon_address FLOAT,
    log_reviews FLOAT,
    avg_cdc_success_rate_vs_national FLOAT,
    annual_cycles_vs_national FLOAT,
    norm_annual_cycles FLOAT,
    norm_avg_cdc_success_rate FLOAT,
    norm_avg_doctor_score FLOAT,
    norm_avg_rating FLOAT,
    norm_log_reviews FLOAT,

    UNIQUE (name, zip_code)
);
